### PR TITLE
Simple style update to the dropdown of the main nav

### PR DESCRIPTION
**Pull request by craigmacgregor**
removed the underline from the dropdown and added some movement to the arrows on hover.

### CODE REVIEW

**Comment by IfaqYurmama** [comment]
I would suggest to add

`.sub-menu li a:hover {
    background-color: rgb(127,127,127,0.1);
}`

additionally so the dropdown menu gets a light shade because especially the last elements bottom border is hardly noticable on hover.

**Comment by matt-auckland** [comment]
Looks good 👍

**Comment by craigmacgregor** [comment]
@IfaqYurmama this has been done

**Comment by matt-auckland** [comment]
Can this be merged? @craigmacgregor

**Pull request merged**
